export const USER_LOADING = 'USER_LOADING';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_ONE_USER = 'FETCH_ONE_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const ADD_USER = 'ADD_USER';
export const DELETE_USER = 'DELETE_USER';
export const USER_FAIL = 'USER_FAIL';
export const CLEAR_USER_FAILURE = 'CLEAR_USER_FAILURE';
